apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kiara-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.100.200-192.168.100.201
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - kiara-ip-pool